name: CI - Bayrou Functions

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node dependencies
        working-directory: front
        run: npm install

      - name: Build Frontend
        working-directory: front
        run: npm run build

      - name: Run tests
        working-directory: api
        run: pytest

  deploy-api:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: "bayrou-functions"
          package: "./api"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
